### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by gauravchauhan2403** [VineetS086/email-app#3]
ADD a navbar with menu button , home button and logo of oue mailing app.

**Comment by MAHIMA01** [comment]
Please can I work on this issue too?

**Comment by aka-vm** [comment]
Go on...
@MAHIMA01

**Comment by MAHIMA01** [comment]
I have opened a pull request with required changes, please accept it and add hacktoberfest-accepted label to the same. If any more changes are required, kindly let me know so that I can do it asap. Thanks!
