### ISSUE TITLE
Design a Signup confirmation mail using HTML+Css

### ISSUE THREAD

**Issue by aka-vm** [VineetS086/email-app#36]
Design a Signup confirmation mail using HTML...
We'll be sending it for email confirmation...

NOTE: Try using style attribute for CSS...

**Comment by gauravchauhan2403** [comment]
Can you elaborate?

**Comment by aka-vm** [comment]
write an email's body with Html and <style> tag.
we are going to send it to the user for signup verification.
it will have a link, which when opened verifies the user...
