### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by gauravchauhan2403** [VineetS086/email-app#4]
Add a footer with contact details and other useful informations

**Comment by MAHIMA01** [comment]
Can I work on this part please?

**Comment by gauravchauhan2403** [comment]
Go Ahead!

**Comment by MAHIMA01** [comment]
> Go Ahead!

I have started working on this issue, can you please share contact details that need to be added or shall I add dummy details? Also I wanted to confirm if I need to make changes to [index.html](https://github.com/VineetS086/email-app/blob/main/index.html) file or [login.html](https://github.com/VineetS086/email-app/blob/main/login.html) file.

**Comment by gauravchauhan2403** [comment]
> > Go Ahead!
> 
> I have started working on this issue, can you please share contact details that need to be added or shall I add dummy details? Also I wanted to confirm if I need to make changes to [index.html](https://github.com/VineetS086/email-app/blob/main/index.html) file or [login.html](https://github.com/VineetS086/email-app/blob/main/login.html) file.

Nice that you have started. For contact details only write our Gmail (emailsender.smvdu@gmail.com) for now and mention for copyright only. While sending PR please attach some screenshots of your working project too.

**Comment by MAHIMA01** [comment]
> > > Go Ahead!
> > 
> > 
> > I have started working on this issue, can you please share contact details that need to be added or shall I add dummy details? Also I wanted to confirm if I need to make changes to [index.html](https://github.com/VineetS086/email-app/blob/main/index.html) file or [login.html](https://github.com/VineetS086/email-app/blob/main/login.html) file.
> 
> Nice that you have started. For contact details only write our Gmail ([emailsender.smvdu@gmail.com](mailto:emailsender.smvdu@gmail.com)) for now and mention for copyright only. While sending PR please attach some screenshots of your working project too.

Okay, thank you will do as asked.
