### ISSUE TITLE
Signup page

### ISSUE THREAD

**Issue by gauravchauhan2403** [VineetS086/email-app#7]
Add a signup page with all useful details.

**Comment by gauravchauhan2403** [comment]
I want to work on this issue. assign this to me .

**Comment by MAHIMA01** [comment]
If this issue is still not completed, can I work on this?

**Comment by aka-vm** [comment]
@gauravchauhan2403  is working on it...
@MAHIMA01  you can work on the navbar or footer if you want...

**Comment by gauravchauhan2403** [comment]
done
